#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# File Options
files:
  include: 'sass/**/*.sass'
  ignore:
    - 'sass/vendor/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1
  mixins-before-declarations:
    - 1
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 1
  hex-notation:
    - 1
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
